const arbeidskategori = {
  FISKER: 'FISKER',
  ARBEIDSTAKER: 'ARBEIDSTAKER',
  SELVSTENDIG_NAERINGSDRIVENDE: 'SELVSTENDIG_NÆRINGSDRIVENDE',
  KOMBINASJON_ARBEIDSTAKER_OG_SELVSTENDIG_NAERINGSDRIVENDE: 'KOMBINASJON_ARBEIDSTAKER_OG_SELVSTENDIG_NÆRINGSDRIVENDE',
  SJOMANN: 'SJØMANN',
  JORDBRUKER: 'JORDBRUKER',
  DAGPENGER: 'DAGPENGER',
  INAKTIV: 'INAKTIV',
  KOMBINASJON_ARBEIDSTAKER_OG_JORDBRUKER: 'KOMBINASJON_ARBEIDSTAKER_OG_JORDBRUKER',
  KOMBINASJON_ARBEIDSTAKER_OG_FISKER: 'KOMBINASJON_ARBEIDSTAKER_OG_FISKER',
  FRILANSER: 'FRILANSER',
  KOMBINASJON_ARBEIDSTAKER_OG_FRILANSER: 'KOMBINASJON_ARBEIDSTAKER_OG_FRILANSER',
  KOMBINASJON_ARBEIDSTAKER_OG_DAGPENGER: 'KOMBINASJON_ARBEIDSTAKER_OG_DAGPENGER',
  DAGMAMMA: 'DAGMAMMA',
  ANNET: 'ANNET',
};

export default arbeidskategori;
