const opplysningAdresseType = {
  BOSTEDSADRESSE: 'BOSTEDSADRESSE',
  POSTADRESSE: 'POSTADRESSE',
  UTENLANDSK_POSTADRESSE: 'POSTADRESSE_UTLAND',
  NORSK_NAV_TILLEGGSADRESSE: 'MIDLERTIDIG_POSTADRESSE_NORGE',
  UTENLANDSK_NAV_TILLEGSADRESSE: 'MIDLERTIDIG_POSTADRESSE_UTLAND',
  UKJENT: 'UKJENT_ADRESSE',
};

export default opplysningAdresseType;
