const overforingArsak = {
  INSTITUSJONSOPPHOLD_ANNEN_FORELDER: 'INSTITUSJONSOPPHOLD_ANNEN_FORELDER',
  SYKDOM_ANNEN_FORELDER: 'SYKDOM_ANNEN_FORELDER',
  UDEFINERT: '-',
};

export default overforingArsak;
