const relatertYtelseType = {
  ENGANGSSTONAD: 'ENGANGSSTØNAD',
  DAGPENGER: 'DAGPENGER',
  FORELDREPENGER: 'FORELDREPENGER',
  SYKEPENGER: 'SYKEPENGER',
  ENSLIG_FORSORGER: 'ENSLIG_FORSØRGER',
  ARBEIDSAVKLARINGSPENGER: 'ARBEIDSAVKLARINGSPENGER',
  SVANGERSKAPSPENGER: 'SVANGERSKAPSPENGER',
  PÅRØRENDESYKDOM: 'PÅRØRENDESYKDOM',
};

export default relatertYtelseType;
