const uttakPeriodeType = {
  MODREKVOTE: 'MØDREKVOTE',
  FEDREKVOTE: 'FEDREKVOTE',
  FELLESPERIODE: 'FELLESPERIODE',
  FORELDREPENGER_FOR_FODSEL: 'FORELDREPENGER_FØR_FØDSEL',
  FORELDREPENGER: 'FORELDREPENGER',
  ANNET: 'ANNET',
  UDEFINERT: '-',
};

export const stonadskontoType = {
  MØDREKVOTE: 'MØDREKVOTE',
  FEDREKVOTE: 'FEDREKVOTE',
  FELLESPERIODE: 'FELLESPERIODE',
  FORELDREPENGER_FØR_FØDSEL: 'FORELDREPENGER_FØR_FØDSEL',
  FORELDREPENGER: 'FORELDREPENGER',
};

export const uttakPeriodeNavn = {
  MØDREKVOTE: 'Mødrekvote',
  FEDREKVOTE: 'Fedrekvote',
  FELLESPERIODE: 'Fellesperiode',
  FORELDREPENGER_FØR_FØDSEL: 'Foreldrepenger før fødsel',
  FORELDREPENGER: 'Foreldrepenger',
  ANNET: 'Annet',
  UDEFINERT: '-',
};

export default uttakPeriodeType;
