const arbeidsforholdHandling = {
  AKTIVT_ARBEIDSFORHOLD: 'AKTIVT_ARBEIDSFORHOLD',
  FJERN_ARBEIDSFORHOLD: 'FJERN_ARBEIDSFORHOLD',
  OVERSTYR_TOM: 'OVERSTYR_TOM',
  SOKER_ER_I_PERMISJON: 'SOKER_ER_I_PERMISJON',
};

export default arbeidsforholdHandling;
