export const beregningsgrunnlag = {
  skjaeringstidspunktBeregning: '2019-03-05',
  skjæringstidspunkt: '2019-03-05',
  aktivitetStatus: [{
    kodeverk: 'AKTIVITET_STATUS',
    kode: 'AT_SN',
  }],
  beregningsgrunnlagPeriode: [{
    beregningsgrunnlagPeriodeFom: '2019-03-05',
    beregningsgrunnlagPeriodeTom: '2019-11-03',
    beregnetPrAar: 663552.0,
    bruttoPrAar: 663552.0,
    bruttoInkludertBortfaltNaturalytelsePrAar: 663552.0,
    periodeAarsaker: [],
    dagsats: 0,
    beregningsgrunnlagPrStatusOgAndel: [{
      dtoType: 'GENERELL',
      beregningsgrunnlagTom: '2019-02-28',
      beregningsgrunnlagFom: '2018-12-01',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'AT',
      },
      beregningsperiodeFom: '2018-12-01',
      beregningsperiodeTom: '2019-02-28',
      beregnetPrAar: 663552.0,
      bruttoPrAar: 663552.0,
      andelsnr: 1,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'ARBEIDSTAKER',
      },
      arbeidsforhold: {
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '123456789',
        arbeidsgiverIdVisning: '123456789',
        startdato: '2017-03-01',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 0.0,
        belopFraInntektsmeldingPrMnd: 55296,
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 40877.6666666667,
      belopPrAarEtterAOrdningen: 490532.0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: false,
    }, {
      dtoType: 'SN',
      beregningsgrunnlagTom: '2017-12-31',
      beregningsgrunnlagFom: '2015-01-01',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'SN',
      },
      beregningsperiodeFom: '2015-01-01',
      beregningsperiodeTom: '2017-12-31',
      beregnetPrAar: 0.0,
      overstyrtPrAar: 0.0,
      bruttoPrAar: 0.0,
      andelsnr: 2,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'SELVSTENDIG_NÆRINGSDRIVENDE',
      },
      arbeidsforhold: {
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'NÆRING',
        },
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      dagsats: 0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: true,
      pgiSnitt: 403557,
      pgiVerdier: [{
        beløp: 494006,
        årstall: 2017,
      }, {
        beløp: 384757,
        årstall: 2016,
      }, {
        beløp: 331908,
        årstall: 2015,
      }],
      næringer: [{
        orgnr: '991561692',
        erVarigEndret: true,
        erNyoppstartet: false,
        virksomhetType: {
          kodeverk: 'VIRKSOMHET_TYPE',
          kode: 'ANNEN',
        },
        endringsdato: '2017-01-01',
        kanRegnskapsførerKontaktes: false,
        erNyIArbeidslivet: false,
        oppgittInntekt: 24425,
      }],
    }],
  }, {
    beregningsgrunnlagPeriodeFom: '2019-11-04',
    beregningsgrunnlagPeriodeTom: '2019-12-09',
    beregnetPrAar: 663552.0,
    bruttoPrAar: 663552.0,
    bruttoInkludertBortfaltNaturalytelsePrAar: 663552.0,
    periodeAarsaker: [{
      kodeverk: 'PERIODE_AARSAK',
      kode: 'GRADERING',
    }],
    dagsats: 0,
    beregningsgrunnlagPrStatusOgAndel: [{
      dtoType: 'GENERELL',
      beregningsgrunnlagTom: '2019-02-28',
      beregningsgrunnlagFom: '2018-12-01',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'AT',
      },
      beregningsperiodeFom: '2018-12-01',
      beregningsperiodeTom: '2019-02-28',
      beregnetPrAar: 663552.0,
      bruttoPrAar: 663552.0,
      andelsnr: 1,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'ARBEIDSTAKER',
      },
      arbeidsforhold: {
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '123456789',
        arbeidsgiverIdVisning: '123456789',
        startdato: '2017-03-01',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 0.0,
        belopFraInntektsmeldingPrMnd: 55296,
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 40877.6666666667,
      belopPrAarEtterAOrdningen: 490532.0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: false,
    }, {
      dtoType: 'SN',
      beregningsgrunnlagTom: '2017-12-31',
      beregningsgrunnlagFom: '2015-01-01',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'SN',
      },
      beregningsperiodeFom: '2015-01-01',
      beregningsperiodeTom: '2017-12-31',
      beregnetPrAar: 0.0,
      overstyrtPrAar: 0.0,
      bruttoPrAar: 0.0,
      andelsnr: 2,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'SELVSTENDIG_NÆRINGSDRIVENDE',
      },
      arbeidsforhold: {
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'NÆRING',
        },
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      dagsats: 0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: true,
      pgiSnitt: 403557,
      pgiVerdier: [{
        beløp: 494006,
        årstall: 2017,
      }, {
        beløp: 384757,
        årstall: 2016,
      }, {
        beløp: 331908,
        årstall: 2015,
      }],
      næringer: [{
        orgnr: '991561692',
        erVarigEndret: true,
        erNyoppstartet: false,
        virksomhetType: {
          kodeverk: 'VIRKSOMHET_TYPE',
          kode: 'ANNEN',
        },
        endringsdato: '2017-01-01',
        kanRegnskapsførerKontaktes: false,
        erNyIArbeidslivet: false,
        oppgittInntekt: 24425,
      }],
    }],
  }, {
    beregningsgrunnlagPeriodeFom: '2019-12-10',
    beregningsgrunnlagPeriodeTom: '9999-12-31',
    beregnetPrAar: 663552.0,
    bruttoPrAar: 663552.0,
    bruttoInkludertBortfaltNaturalytelsePrAar: 663552.0,
    periodeAarsaker: [{
      kodeverk: 'PERIODE_AARSAK',
      kode: 'GRADERING_OPPHØRER',
    }],
    dagsats: 0,
    beregningsgrunnlagPrStatusOgAndel: [{
      dtoType: 'GENERELL',
      beregningsgrunnlagTom: '2019-02-28',
      beregningsgrunnlagFom: '2018-12-01',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'AT',
      },
      beregningsperiodeFom: '2018-12-01',
      beregningsperiodeTom: '2019-02-28',
      beregnetPrAar: 663552.0,
      bruttoPrAar: 663552.0,
      andelsnr: 1,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'ARBEIDSTAKER',
      },
      arbeidsforhold: {
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '123456789',
        arbeidsgiverIdVisning: '123456789',
        startdato: '2017-03-01',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 0.0,
        belopFraInntektsmeldingPrMnd: 55296,
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 40877.6666666667,
      belopPrAarEtterAOrdningen: 490532.0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: false,
    }, {
      dtoType: 'SN',
      beregningsgrunnlagTom: '2017-12-31',
      beregningsgrunnlagFom: '2015-01-01',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'SN',
      },
      beregningsperiodeFom: '2015-01-01',
      beregningsperiodeTom: '2017-12-31',
      beregnetPrAar: 0.0,
      overstyrtPrAar: 0.0,
      bruttoPrAar: 0.0,
      andelsnr: 2,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'SELVSTENDIG_NÆRINGSDRIVENDE',
      },
      arbeidsforhold: {
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'NÆRING',
        },
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      dagsats: 0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: true,
      pgiSnitt: 403557,
      pgiVerdier: [{
        beløp: 494006,
        årstall: 2017,
      }, {
        beløp: 384757,
        årstall: 2016,
      }, {
        beløp: 331908,
        årstall: 2015,
      }],
      næringer: [{
        orgnr: '991561692',
        erVarigEndret: true,
        erNyoppstartet: false,
        virksomhetType: {
          kodeverk: 'VIRKSOMHET_TYPE',
          kode: 'ANNEN',
        },
        endringsdato: '2017-01-01',
        kanRegnskapsførerKontaktes: false,
        erNyIArbeidslivet: false,
        oppgittInntekt: 24425,
      }],
    }],
  }],
  sammenligningsgrunnlag: {
    sammenligningsgrunnlagFom: '2017-01-01',
    sammenligningsgrunnlagTom: '2017-01-31',
    rapportertPrAar: 687977.0,
    avvikPromille: 704.7833284,
    avvikProsent: 70.47833284,
    sammenligningsgrunnlagType: {
      kodeverk: 'SAMMENLIGNINGSGUNNLAG_TYPE',
      kode: 'SAMMENLIGNING_ATFL_SN',
    },
    differanseBeregnet: -284420.0,
  },
  sammenligningsgrunnlagPrStatus: [{
    sammenligningsgrunnlagFom: '2017-01-01',
    sammenligningsgrunnlagTom: '2017-01-31',
    rapportertPrAar: 687977.0,
    avvikPromille: 704.7833284,
    avvikProsent: 70.47833284,
    sammenligningsgrunnlagType: {
      kodeverk: 'SAMMENLIGNINGSGUNNLAG_TYPE',
      kode: 'SAMMENLIGNING_ATFL_SN',
    },
    differanseBeregnet: -284420.0,
  }],
  ledetekstBrutto: 'Brutto beregningsgrunnlag',
  ledetekstAvkortet: 'Avkortet beregningsgrunnlag (6G=581298)',
  ledetekstRedusert: 'Redusert beregningsgrunnlag (100%)',
  halvG: 48441.5,
  grunnbeløp: 96883.0,
  faktaOmBeregning: {
    avklarAktiviteter: {
      aktiviteterTomDatoMapping: [{
        tom: '2019-03-05',
        aktiviteter: [{
          fom: '2007-08-09',
          tom: '9999-12-31',
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'NÆRING',
          },
        }, {
          arbeidsgiverNavn: 'Arbeidsgiveren',
          arbeidsgiverId: '123456789',
          fom: '2017-03-01',
          tom: '9999-12-31',
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }, {
          fom: '2019-02-01',
          tom: '2019-03-04',
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'SVANGERSKAPSPENGER',
          },
        }],
      }, {
        tom: '2018-09-02',
        aktiviteter: [{
          arbeidsgiverNavn: 'Arbeidsgiveren',
          arbeidsgiverId: '123456700',
          fom: '2018-01-10',
          tom: '2018-09-01',
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }],
      }],
    },
    andelerForFaktaOmBeregning: [{
      belopReadOnly: 55296,
      fastsattBelop: 55296.0,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'ARBEIDSTAKER',
      },
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'AT',
      },
      visningsnavn: 'Arbeidsgiveren (123456789)',
      arbeidsforhold: {
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '123456789',
        arbeidsgiverIdVisning: '123456789',
        startdato: '2017-03-01',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 0.0,
        belopFraInntektsmeldingPrMnd: 55296,
      },
      andelsnr: 1,
      skalKunneEndreAktivitet: false,
      lagtTilAvSaksbehandler: false,
    }, {
      fastsattBelop: 0.0,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'SELVSTENDIG_NÆRINGSDRIVENDE',
      },
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'SN',
      },
      visningsnavn: 'Næring',
      arbeidsforhold: {
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'NÆRING',
        },
      },
      andelsnr: 2,
      skalKunneEndreAktivitet: false,
      lagtTilAvSaksbehandler: false,
    }],
  },
  hjemmel: {
    kodeverk: 'BG_HJEMMEL',
    kode: 'F_14_7_8_41',
  },
  faktaOmFordeling: {
    fordelBeregningsgrunnlag: {
      fordelBeregningsgrunnlagPerioder: [{
        fom: '2019-03-05',
        tom: '2019-11-03',
        fordelBeregningsgrunnlagAndeler: [{
          andelsnr: 1,
          arbeidsforhold: {
            arbeidsgiverNavn: 'Arbeidsgiveren',
            arbeidsgiverId: '123456789',
            arbeidsgiverIdVisning: '123456789',
            startdato: '2017-03-01',
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'ARBEID',
            },
            refusjonPrAar: 0.0,
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'ARBEIDSTAKER',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'AT',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [20, 20],
          refusjonskravPrAar: 0,
          belopFraInntektsmeldingPrAar: 663552,
          refusjonskravFraInntektsmeldingPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }, {
          andelsnr: 2,
          arbeidsforhold: {
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'NÆRING',
            },
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'SELVSTENDIG_NÆRINGSDRIVENDE',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'SN',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'NÆRING',
          },
        }],
        skalRedigereInntekt: false,
        skalPreutfyllesMedBeregningsgrunnlag: false,
        skalKunneEndreRefusjon: false,
      }, {
        fom: '2019-11-04',
        tom: '2019-12-09',
        fordelBeregningsgrunnlagAndeler: [{
          andelsnr: 1,
          arbeidsforhold: {
            arbeidsgiverNavn: 'Arbeidsgiveren',
            arbeidsgiverId: '123456789',
            arbeidsgiverIdVisning: '123456789',
            startdato: '2017-03-01',
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'ARBEID',
            },
            refusjonPrAar: 0.0,
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'ARBEIDSTAKER',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'AT',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          belopFraInntektsmeldingPrAar: 663552,
          refusjonskravFraInntektsmeldingPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }, {
          andelsnr: 2,
          arbeidsforhold: {
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'NÆRING',
            },
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'SELVSTENDIG_NÆRINGSDRIVENDE',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'SN',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [50],
          refusjonskravPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'NÆRING',
          },
        }],
        skalRedigereInntekt: true,
        skalPreutfyllesMedBeregningsgrunnlag: false,
        skalKunneEndreRefusjon: false,
      }, {
        fom: '2019-12-10',
        tom: '9999-12-31',
        fordelBeregningsgrunnlagAndeler: [{
          andelsnr: 1,
          arbeidsforhold: {
            arbeidsgiverNavn: 'Arbeidsgiveren',
            arbeidsgiverId: '123456789',
            arbeidsgiverIdVisning: '123456789',
            startdato: '2017-03-01',
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'ARBEID',
            },
            refusjonPrAar: 0.0,
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'ARBEIDSTAKER',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'AT',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          belopFraInntektsmeldingPrAar: 663552,
          refusjonskravFraInntektsmeldingPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }, {
          andelsnr: 2,
          arbeidsforhold: {
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'NÆRING',
            },
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'SELVSTENDIG_NÆRINGSDRIVENDE',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'SN',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'NÆRING',
          },
        }],
        skalRedigereInntekt: true,
        skalPreutfyllesMedBeregningsgrunnlag: true,
        skalKunneEndreRefusjon: false,
      }],
      arbeidsforholdTilFordeling: [{
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'NÆRING',
        },
        perioderMedGraderingEllerRefusjon: [{
          erRefusjon: false,
          erGradering: true,
          erSøktYtelse: false,
          fom: '2019-11-04',
          tom: '2019-12-09',
        }],
      }],
    },
  },
  årsinntektVisningstall: 403557,
  dekningsgrad: 100,
};

export const aksjonspunkt = [
  {
    definisjon: { kode: '5046', kodeverk: 'AKSJONSPUNKT_DEF' },
    status: { kode: 'OPPR', kodeverk: 'AKSJONSPUNKT_STATUS' },
    begrunnelse: null,
    vilkarType: null,
    toTrinnsBehandling: true,
    toTrinnsBehandlingGodkjent: null,
    vurderPaNyttArsaker: null,
    besluttersBegrunnelse: null,
    aksjonspunktType: { kode: 'MANU', kodeverk: 'AKSJONSPUNKT_TYPE' },
    kanLoses: true,
    erAktivt: true,
    fristTid: null,
    endretTidspunkt: null,
    endretAv: null,
  }];
