export const beregningsgrunnlag = {
  skjaeringstidspunktBeregning: '2019-12-14',
  skjæringstidspunkt: '2019-12-14',
  aktivitetStatus: [{
    kodeverk: 'AKTIVITET_STATUS',
    kode: 'AT_FL',
  }],
  beregningsgrunnlagPeriode: [{
    beregningsgrunnlagPeriodeFom: '2019-12-14',
    beregningsgrunnlagPeriodeTom: '2019-12-15',
    beregnetPrAar: 456120.0,
    bruttoPrAar: 456120.0,
    bruttoInkludertBortfaltNaturalytelsePrAar: 456120.0,
    periodeAarsaker: [],
    beregningsgrunnlagPrStatusOgAndel: [{
      dtoType: 'GENERELL',
      beregningsgrunnlagFom: '2019-09-01',
      beregningsgrunnlagTom: '2019-11-30',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'AT',
      },
      beregningsperiodeFom: '2019-09-01',
      beregningsperiodeTom: '2019-11-30',
      beregnetPrAar: 456120.0,
      bruttoPrAar: 456120.0,
      andelsnr: 2,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'ARBEIDSTAKER',
      },
      arbeidsforhold: {
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '922745943',
        arbeidsgiverIdVisning: '922745943',
        startdato: '2019-08-01',
        opphoersdato: '2020-01-31',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 0.0,
        belopFraInntektsmeldingPrMnd: 38010,
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 38010.25,
      belopPrAarEtterAOrdningen: 456123.0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: false,
    }, {
      dtoType: 'FL',
      beregningsgrunnlagFom: '2019-09-01',
      beregningsgrunnlagTom: '2019-11-30',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'FL',
      },
      beregningsperiodeFom: '2019-09-01',
      beregningsperiodeTom: '2019-11-30',
      beregnetPrAar: 0.0,
      bruttoPrAar: 0.0,
      andelsnr: 1,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'FRILANSER',
      },
      arbeidsforhold: {
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'FRILANS',
        },
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 0.0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: false,
    }],
  }, {
    beregningsgrunnlagPeriodeFom: '2019-12-16',
    beregningsgrunnlagPeriodeTom: '2020-02-02',
    beregnetPrAar: 456120.0,
    bruttoPrAar: 456120.0,
    bruttoInkludertBortfaltNaturalytelsePrAar: 462120.0,
    periodeAarsaker: [{
      kodeverk: 'PERIODE_AARSAK',
      kode: 'NATURALYTELSE_BORTFALT',
    }],
    beregningsgrunnlagPrStatusOgAndel: [{
      dtoType: 'AT',
      beregningsgrunnlagFom: '2019-09-01',
      beregningsgrunnlagTom: '2019-11-30',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'AT',
      },
      beregningsperiodeFom: '2019-09-01',
      beregningsperiodeTom: '2019-11-30',
      beregnetPrAar: 456120.0,
      bruttoPrAar: 456120.0,
      andelsnr: 2,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'ARBEIDSTAKER',
      },
      arbeidsforhold: {
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '922745943',
        arbeidsgiverIdVisning: '922745943',
        startdato: '2019-08-01',
        opphoersdato: '2020-01-31',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 0.0,
        belopFraInntektsmeldingPrMnd: 38010,
        naturalytelseBortfaltPrÅr: 6000.0,
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 38010.25,
      belopPrAarEtterAOrdningen: 456123.0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: false,
      bortfaltNaturalytelse: 6000.0,
    }, {
      dtoType: 'FL',
      beregningsgrunnlagFom: '2019-09-01',
      beregningsgrunnlagTom: '2019-11-30',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'FL',
      },
      beregningsperiodeFom: '2019-09-01',
      beregningsperiodeTom: '2019-11-30',
      beregnetPrAar: 0.0,
      bruttoPrAar: 0.0,
      andelsnr: 1,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'FRILANSER',
      },
      arbeidsforhold: {
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'FRILANS',
        },
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 0.0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: false,
    }],
  }, {
    beregningsgrunnlagPeriodeFom: '2020-02-03',
    beregningsgrunnlagPeriodeTom: '9999-12-31',
    beregnetPrAar: 456120.0,
    bruttoPrAar: 456120.0,
    bruttoInkludertBortfaltNaturalytelsePrAar: 462120.0,
    periodeAarsaker: [{
      kodeverk: 'PERIODE_AARSAK',
      kode: 'ENDRING_I_REFUSJONSKRAV',
    }],
    beregningsgrunnlagPrStatusOgAndel: [{
      dtoType: 'AT',
      beregningsgrunnlagFom: '2019-09-01',
      beregningsgrunnlagTom: '2019-11-30',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'AT',
      },
      beregningsperiodeFom: '2019-09-01',
      beregningsperiodeTom: '2019-11-30',
      beregnetPrAar: 456120.0,
      bruttoPrAar: 456120.0,
      andelsnr: 2,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'ARBEIDSTAKER',
      },
      arbeidsforhold: {
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '922745943',
        arbeidsgiverIdVisning: '922745943',
        startdato: '2019-08-01',
        opphoersdato: '2020-01-31',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 0.0,
        belopFraInntektsmeldingPrMnd: 38010,
        naturalytelseBortfaltPrÅr: 6000.0,
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 38010.25,
      belopPrAarEtterAOrdningen: 456123.0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: false,
      bortfaltNaturalytelse: 6000.0,
    }, {
      dtoType: 'GENERELL',
      beregningsgrunnlagFom: '2019-09-01',
      beregningsgrunnlagTom: '2019-11-30',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'AT',
      },
      beregningsperiodeFom: '2019-09-01',
      beregningsperiodeTom: '2019-11-30',
      andelsnr: 3,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: '-',
      },
      arbeidsforhold: {
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '883551222',
        arbeidsgiverIdVisning: '883551222',
        startdato: '2020-01-01',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 470238.0,
        belopFraInntektsmeldingPrMnd: 39186.5,
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 0.0,
      belopPrAarEtterAOrdningen: 0.0,
      erTilkommetAndel: true,
      skalFastsetteGrunnlag: false,
    }, {
      dtoType: 'FL',
      beregningsgrunnlagFom: '2019-09-01',
      beregningsgrunnlagTom: '2019-11-30',
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'FL',
      },
      beregningsperiodeFom: '2019-09-01',
      beregningsperiodeTom: '2019-11-30',
      beregnetPrAar: 0.0,
      bruttoPrAar: 0.0,
      andelsnr: 1,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'FRILANSER',
      },
      arbeidsforhold: {
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'FRILANS',
        },
      },
      fastsattAvSaksbehandler: false,
      lagtTilAvSaksbehandler: false,
      belopPrMndEtterAOrdningen: 0.0,
      erTilkommetAndel: false,
      skalFastsetteGrunnlag: false,
    }],
  }],
  sammenligningsgrunnlag: {
    sammenligningsgrunnlagFom: '2018-12-01',
    sammenligningsgrunnlagTom: '2019-11-30',
    rapportertPrAar: 461946.28,
    avvikPromille: 12.6124622,
    avvikProsent: 1.26124622,
    sammenligningsgrunnlagType: {
      kodeverk: 'SAMMENLIGNINGSGUNNLAG_TYPE',
      kode: 'SAMMENLIGNING_ATFL_SN',
    },
    differanseBeregnet: -5826.28,
  },
  sammenligningsgrunnlagPrStatus: [{
    sammenligningsgrunnlagFom: '2018-12-01',
    sammenligningsgrunnlagTom: '2019-11-30',
    rapportertPrAar: 461946.28,
    avvikPromille: 12.6124622,
    avvikProsent: 1.26124622,
    sammenligningsgrunnlagType: {
      kodeverk: 'SAMMENLIGNINGSGUNNLAG_TYPE',
      kode: 'SAMMENLIGNING_ATFL_SN',
    },
    differanseBeregnet: -5826.28,
  }],
  ledetekstBrutto: 'Brutto beregningsgrunnlag',
  ledetekstAvkortet: 'Avkortet beregningsgrunnlag (6G=599148)',
  ledetekstRedusert: 'Redusert beregningsgrunnlag (100%)',
  halvG: 49929.0,
  grunnbeløp: 99858.0,
  faktaOmBeregning: {
    frilansAndel: {
      andelsnr: 1,
      arbeidsforhold: {
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'FRILANS',
        },
      },
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'FRILANSER',
      },
      lagtTilAvSaksbehandler: false,
      fastsattAvSaksbehandler: false,
      andelIArbeid: [],
    },
    faktaOmBeregningTilfeller: [{
      kodeverk: 'FAKTA_OM_BEREGNING_TILFELLE',
      kode: 'VURDER_MOTTAR_YTELSE',
    }],
    vurderMottarYtelse: {
      erFrilans: true,
      frilansMottarYtelse: true,
      frilansInntektPrMnd: 0.0,
      arbeidstakerAndelerUtenIM: [],
    },
    avklarAktiviteter: {
      aktiviteterTomDatoMapping: [{
        tom: '2019-12-14',
        aktiviteter: [{
          fom: '2013-04-01',
          tom: '9999-12-31',
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'FRILANS',
          },
        }, {
          fom: '2019-06-12',
          tom: '2019-12-15',
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'SYKEPENGER',
          },
        }, {
          arbeidsgiverNavn: 'Arbeidsgiveren',
          arbeidsgiverId: '922745943',
          fom: '2019-08-01',
          tom: '2020-01-31',
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }],
      }, {
        tom: '2019-08-01',
        aktiviteter: [{
          arbeidsgiverNavn: 'Arbeidsgiveren',
          arbeidsgiverId: '991945970',
          fom: '2018-02-01',
          tom: '2019-07-31',
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }],
      }],
    },
    andelerForFaktaOmBeregning: [{
      belopReadOnly: 0.0,
      fastsattBelop: 0.0,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'FRILANSER',
      },
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'FL',
      },
      visningsnavn: 'Frilans',
      arbeidsforhold: {
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'FRILANS',
        },
      },
      andelsnr: 1,
      skalKunneEndreAktivitet: false,
      lagtTilAvSaksbehandler: false,
    }, {
      belopReadOnly: 38010,
      fastsattBelop: 38010.0,
      inntektskategori: {
        kodeverk: 'INNTEKTSKATEGORI',
        kode: 'ARBEIDSTAKER',
      },
      aktivitetStatus: {
        kodeverk: 'AKTIVITET_STATUS',
        kode: 'AT',
      },
      visningsnavn: 'Arbeidsgiveren (922745943)',
      arbeidsforhold: {
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '922745943',
        arbeidsgiverIdVisning: '922745943',
        startdato: '2019-08-01',
        opphoersdato: '2020-01-31',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 0.0,
        belopFraInntektsmeldingPrMnd: 38010,
      },
      andelsnr: 2,
      skalKunneEndreAktivitet: false,
      lagtTilAvSaksbehandler: false,
    }],
    vurderMilitaer: {
      harMilitaer: false,
    },
  },
  hjemmel: {
    kodeverk: 'BG_HJEMMEL',
    kode: 'F_14_7_8_40',
  },
  faktaOmFordeling: {
    fordelBeregningsgrunnlag: {
      fordelBeregningsgrunnlagPerioder: [{
        fom: '2019-12-14',
        tom: '2019-12-15',
        fordelBeregningsgrunnlagAndeler: [{
          andelsnr: 1,
          arbeidsforhold: {
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'FRILANS',
            },
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'FRILANSER',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'FL',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'FRILANS',
          },
        }, {
          andelsnr: 2,
          arbeidsforhold: {
            arbeidsgiverNavn: 'Arbeidsgiveren',
            arbeidsgiverId: '922745943',
            arbeidsgiverIdVisning: '922745943',
            startdato: '2019-08-01',
            opphoersdato: '2020-01-31',
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'ARBEID',
            },
            refusjonPrAar: 0.0,
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'ARBEIDSTAKER',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'AT',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          belopFraInntektsmeldingPrAar: 456120,
          refusjonskravFraInntektsmeldingPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }],
        skalRedigereInntekt: false,
        skalPreutfyllesMedBeregningsgrunnlag: false,
        skalKunneEndreRefusjon: false,
      }, {
        fom: '2019-12-16',
        tom: '2020-02-02',
        fordelBeregningsgrunnlagAndeler: [{
          andelsnr: 1,
          arbeidsforhold: {
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'FRILANS',
            },
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'FRILANSER',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'FL',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'FRILANS',
          },
        }, {
          andelsnr: 2,
          arbeidsforhold: {
            arbeidsgiverNavn: 'Arbeidsgiveren',
            arbeidsgiverId: '922745943',
            arbeidsgiverIdVisning: '922745943',
            startdato: '2019-08-01',
            opphoersdato: '2020-01-31',
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'ARBEID',
            },
            refusjonPrAar: 0.0,
            naturalytelseBortfaltPrÅr: 6000.0,
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'ARBEIDSTAKER',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'AT',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          belopFraInntektsmeldingPrAar: 456120,
          refusjonskravFraInntektsmeldingPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }],
        skalRedigereInntekt: false,
        skalPreutfyllesMedBeregningsgrunnlag: false,
        skalKunneEndreRefusjon: false,
      }, {
        fom: '2020-02-03',
        tom: '9999-12-31',
        fordelBeregningsgrunnlagAndeler: [{
          andelsnr: 1,
          arbeidsforhold: {
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'FRILANS',
            },
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'FRILANSER',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'FL',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'FRILANS',
          },
        }, {
          andelsnr: 2,
          arbeidsforhold: {
            arbeidsgiverNavn: 'Arbeidsgiveren',
            arbeidsgiverId: '922745943',
            arbeidsgiverIdVisning: '922745943',
            startdato: '2019-08-01',
            opphoersdato: '2020-01-31',
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'ARBEID',
            },
            refusjonPrAar: 0.0,
            naturalytelseBortfaltPrÅr: 6000.0,
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: 'ARBEIDSTAKER',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'AT',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 0,
          belopFraInntektsmeldingPrAar: 456120,
          refusjonskravFraInntektsmeldingPrAar: 0,
          nyttArbeidsforhold: false,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }, {
          andelsnr: 3,
          arbeidsforhold: {
            arbeidsgiverNavn: 'Arbeidsgiveren',
            arbeidsgiverId: '883551222',
            arbeidsgiverIdVisning: '883551222',
            startdato: '2020-01-01',
            arbeidsforholdType: {
              kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
              kode: 'ARBEID',
            },
            refusjonPrAar: 470238.0,
          },
          inntektskategori: {
            kodeverk: 'INNTEKTSKATEGORI',
            kode: '-',
          },
          aktivitetStatus: {
            kodeverk: 'AKTIVITET_STATUS',
            kode: 'AT',
          },
          lagtTilAvSaksbehandler: false,
          fastsattAvSaksbehandler: false,
          andelIArbeid: [0],
          refusjonskravPrAar: 470238,
          belopFraInntektsmeldingPrAar: 470238,
          refusjonskravFraInntektsmeldingPrAar: 470238,
          nyttArbeidsforhold: true,
          arbeidsforholdType: {
            kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
            kode: 'ARBEID',
          },
        }],
        skalRedigereInntekt: true,
        skalPreutfyllesMedBeregningsgrunnlag: false,
        skalKunneEndreRefusjon: false,
      }],
      arbeidsforholdTilFordeling: [{
        arbeidsgiverNavn: 'Arbeidsgiveren',
        arbeidsgiverId: '883551222',
        arbeidsgiverIdVisning: '883551222',
        startdato: '2020-01-01',
        arbeidsforholdType: {
          kodeverk: 'OPPTJENING_AKTIVITET_TYPE',
          kode: 'ARBEID',
        },
        refusjonPrAar: 470238.0,
        perioderMedGraderingEllerRefusjon: [{
          erRefusjon: true,
          erGradering: false,
          erSøktYtelse: false,
          fom: '2020-02-03',
        }],
      }],
    },
  },
  årsinntektVisningstall: 456120.0,
  dekningsgrad: 100,
};

export const aksjonspunkt = [
  {
    definisjon: { kode: '5046', kodeverk: 'AKSJONSPUNKT_DEF' },
    status: { kode: 'OPPR', kodeverk: 'AKSJONSPUNKT_STATUS' },
    begrunnelse: null,
    vilkarType: null,
    toTrinnsBehandling: true,
    toTrinnsBehandlingGodkjent: null,
    vurderPaNyttArsaker: null,
    besluttersBegrunnelse: null,
    aksjonspunktType: { kode: 'MANU', kodeverk: 'AKSJONSPUNKT_TYPE' },
    kanLoses: true,
    erAktivt: true,
    fristTid: null,
    endretTidspunkt: null,
    endretAv: null,
  }];
