const ankeAvvistArsak = {
  ANKE_FOR_SENT: 'ANKE_FOR_SENT',
  ANKE_UGYLDIG: 'ANKE_UGYLDIG',
  ANKE_IKKE_PAANKET_VEDTAK: 'ANKE_IKKE_PAANKET_VEDTAK',
  ANKE_IKKE_PART: 'ANKE_IKKE_PART',
  ANKE_IKKE_KONKRET: 'ANKE_IKKE_KONKRET',
  ANKE_IKKE_SIGNERT: 'ANKE_IKKE_SIGNERT',
};

export default ankeAvvistArsak;
