const arbeidsforholdHandlingType = {
  UDEFINERT: 'UDEFINERT',
  BRUK: 'BRUK',
  NYTT_ARBEIDSFORHOLD: 'NYTT_ARBEIDSFORHOLD',
  BRUK_UTEN_INNTEKTSMELDING: 'BRUK_UTEN_INNTEKTSMELDING',
  IKKE_BRUK: 'IKKE_BRUK',
  SLÅTT_SAMMEN_MED_ANNET: 'SLÅTT_SAMMEN_MED_ANNET',
  LAGT_TIL_AV_SAKSBEHANDLER: 'LAGT_TIL_AV_SAKSBEHANDLER',
  BRUK_MED_OVERSTYRT_PERIODE: 'BRUK_MED_OVERSTYRT_PERIODE',
  INNTEKT_IKKE_MED_I_BG: 'INNTEKT_IKKE_MED_I_BG',
};

export default arbeidsforholdHandlingType;
