const arbeidType = {
  LONN_UNDER_UTDANNING: 'LØNN_UNDER_UTDANNING',
  UTENLANDSK_ARBEIDSFORHOLD: 'UTENLANDSK_ARBEIDSFORHOLD',
  FRILANSER: 'FRILANSER',
  MILITÆR_ELLER_SIVILTJENESTE: 'MILITÆR_ELLER_SIVILTJENESTE',
};

export default arbeidType;
