const avregningCodes = {
  DIFFERANSE: 'differanse',
  INNTREKK: 'inntrekk',
  FEILUTBETALING: 'feilutbetaling',
  INNTREKKNESTEMÅNED: 'inntrekkNesteMåned',
  TILBAKEKR_INFOTRYGD: 'TILBAKEKR_INFOTRYGD',
  TILBAKEKR_IGNORER: 'TILBAKEKR_IGNORER',
  TILBAKEKR_INNTREKK: 'TILBAKEKR_INNTREKK',
  TILBAKEKR_INFOTRYGD_OG_INNTREKK: 'TILBAKEKR_INFOTRYGD_OG_INNTREKK',
  OPPFYLT: 'oppfylt',
  REDUKSJON: 'reduksjon',
};

export default avregningCodes;
