const dokumentMalType = {
  INNHENT_DOK: 'INNHEN',
  REVURDERING_DOK: 'REVURD',
  FORLENGET_DOK: 'FORLEN',
  FORLENGET_MEDL_DOK: 'FORLME',
  VEDTAK_MEDHOLD: 'VEDMED',
  KLAGE_OMGJORING: 'KOMGJO',
  KLAGE_AVVIST_DOK: 'KLAGAV',
  KLAGE_AVVIST: 'KAVVIS',
  KLAGE_YTELSESVEDTAK_STADFESTET_DOK: 'KLAGVE',
  KLAGE_STADFESTET: 'KSTADF',
  KLAGE_YTELSESVEDTAK_OPPHEVET_DOK: 'KLAGNY',
  KLAGE_OVERSENDT_KLAGEINSTANS_DOK: 'KLAGOV',
  ANKE_VEDTAK_OMGJORING: 'VEDOGA',
  ANKE_BESLUTNING_OM_OPPHEVING: 'ANKEBO',
  TBKVAR: 'TBKVAR',
  KORRIGVARS: 'KORRIGVARS',
  FRITKS: 'FRITKS',
  VARSEL_OM_TILBAKEKREVING: 'VARS',
};

export default dokumentMalType;
