const handlingTyper = {
  BRUK: 'BRUK',
  NYTT_ARBEIDSFORHOLD: 'NYTT_ARBEIDSFORHOLD',
  BRUK_UTEN_INNTEKTSMELDING: 'BRUK_UTEN_INNTEKTSMELDING',
  IKKE_BRUK: 'IKKE_BRUK',
  SLÅTT_SAMMEN_MED_ANNET: 'SLÅTT_SAMMEN_MED_ANNET',
  BRUK_MED_OVERSTYRT_PERIODE: 'BRUK_MED_OVERSTYRT_PERIODE',
};

export default handlingTyper;
