const historikkEndretFeltType = {
  ER_VILKARENE_TILBAKEKREVING_OPPFYLT: 'ER_VILKARENE_TILBAKEKREVING_OPPFYLT',
  ANDEL_TILBAKEKREVES: 'ANDEL_TILBAKEKREVES',
  BELOEP_TILBAKEKREVES: 'BELOEP_TILBAKEKREVES',
  ILEGG_RENTER: 'ILEGG_RENTER',
};

export default historikkEndretFeltType;
