const ikkeOppfyltArsak = {
  UKJENT: '-',
  HULL_MELLOM_STØNADSPERIODE: '4005',
  IKKE_STØNADSDAGER_IGJEN: '4002',
  SØKNADSFRIST: '4020',
  BARN_OVER_3_ÅR: '4022',
  FAR_HAR_IKKE_OMSORG: '4012',
  MOR_HAR_IKKE_OMSORG: '4003',
  MOR_SØKER_FELLESPERIODE_FØR_12_UKER_FØR_TERMIN_FØDSEL: '4013',
  FAR_SØKER_FØR_TERMIN_FØDSEL: '4010',
  SAMTIDIG_UTTAK_IKKE_GYLDIG_KOMBINASJON: '4060',
  MOR_SØKER_FELLESPERIODE_FØR_UKE_7: '4014',
  // Overføring årsaker
  DEN_ANDRE_PART_SYK_SKADET_IKKE_OPPFYLT: '4007',
  DEN_ANDRE_PART_INNLEGGELSE_IKKE_OPPFYLT: '4008',
  // Utsettelse årsaker
  IKKE_LOVBESTEMT_FERIE: '4033',
  FERIE_SELVSTENDIG_NÆRINGSDRIVENDSE_FRILANSER: '4032',
  IKKE_HELTIDSARBEID: '4037',
  SØKERS_SYKDOM_SKADE_IKKE_OPPFYLT: '4038',
  SØKERS_INNLEGGELSE_IKKE_OPPFYLT: '4039',
  BARNETS_INNLEGGELSE_IKKE_OPPFYLT: '4040',
  FERIE_INNENFOR_DE_FØRSTE_6_UKENE: '4031',
  INGEN_STØNADSDAGER_IGJEN: '4034',
  FAR_ALENEOMSORG_MOR_FYLLES_IKKE_AKTIVITETSKRAVET: '4035',
  UTSETTELSE_FØR_TERMIN_FØDSEL: '4030',
  UTSETTELSE_FERIE_PÅ_BEVEGELIG_HELLIGDAG: '4041',
};

export default ikkeOppfyltArsak;
