const opptjeningAktivitetType = {
  ARBEID: 'ARBEID',
  AAP: 'AAP',
  DAGPENGER: 'DAGPENGER',
  FORELDREPENGER: 'FORELDREPENGER',
  FRILANS: 'FRILANS',
  MILITAR_ELLER_SIVILTJENESTE: 'MILITÆR_ELLER_SIVILTJENESTE',
  NARING: 'NÆRING',
  OMSORGSPENGER: 'OMSORGSPENGER',
  OPPLARINGSPENGER: 'OPPLÆRINGSPENGER',
  PLEIEPENGER: 'PLEIEPENGER',
  SVANGERSKAPSPENGER: 'SVANGERSKAPSPENGER',
  SYKEPENGER: 'SYKEPENGER',
  VARTPENGER: 'VARTPENGER',
  VIDERE_ETTERUTDANNING: 'VIDERE_ETTERUTDANNING',
  UTENLANDSK_ARBEIDSFORHOLD: 'UTENLANDSK_ARBEIDSFORHOLD',
  VENTELØNN_VARTPENGER: 'VENTELØNN_VARTPENGER',
  ETTERLONN_SLUTTPAKKE: 'ETTERLØNN_SLUTTPAKKE',
};

export default opptjeningAktivitetType;
