const periodeResultatType = {
  INNVILGET: 'INNVILGET',
  AVSLATT: 'AVSLÅTT',
  IKKE_FASTSATT: 'IKKE_FASTSATT',
  GYLDIG_UTSETTELSE: 'GYLDIG_UTSETTELSE',
  UGYLDIG_UTSETTELSE: 'UGYLDIG_UTSETTELSE',
  MANUELL_BEHANDLING: 'MANUELL_BEHANDLING',
};

export default periodeResultatType;
