const tilbakekrevingVidereBehandling = {
  TILBAKEKR_INFOTRYGD: 'TILBAKEKR_INFOTRYGD',
  TILBAKEKR_IGNORER: 'TILBAKEKR_IGNORER',
  TILBAKEKR_INNTREKK: 'TILBAKEKR_INNTREKK',
  TILBAKEKR_OPPDATER: 'TILBAKEKR_OPPDATER',
};

export default tilbakekrevingVidereBehandling;
