const tilretteleggingType = {
  HEL_TILRETTELEGGING: 'HEL_TILRETTELEGGING',
  DELVIS_TILRETTELEGGING: 'DELVIS_TILRETTELEGGING',
  INGEN_TILRETTELEGGING: 'INGEN_TILRETTELEGGING',
};

export default tilretteleggingType;
