const utsettelseArsakCodes = {
  ARBEID: 'ARBEID',
  LOVBESTEMT_FERIE: 'LOVBESTEMT_FERIE',
  SYKDOM: 'SYKDOM',
  INSTITUSJONSOPPHOLD_SØKER: 'INSTITUSJONSOPPHOLD_SØKER',
  INSTITUSJONSOPPHOLD_BARNET: 'INSTITUSJONSOPPHOLD_BARNET',
  HV_OVELSE: 'HV_OVELSE',
  NAV_TILTAK: 'NAV_TILTAK',
  UDEFINERT: '-',
};

export const utsettelseArsakTexts = {
  ARBEID: 'Arbeid',
  LOVBESTEMT_FERIE: 'Ferie',
  SYKDOM: 'Sykdom',
  INSTITUSJONSOPPHOLD_SØKER: 'Innleggelse søker',
  INSTITUSJONSOPPHOLD_BARNET: 'Innleggelse barn',
  UDEFINERT: '-',
};

export default utsettelseArsakCodes;
