const venteArsakType = {
  AVV_DOK: 'AVV_DOK',
  AVV_FODSEL: 'AVV_FODSEL',
  UTV_FRIST: 'UTV_FRIST',
  VENT_GRADERING_UTEN_BEREGNINGSGRUNNLAG: 'VENT_GRADERING_UTEN_BEREGNINGSGRUNNLAG',
  VENT_PÅ_TILBAKEKREVINGSGRUNNLAG: 'VENT_PÅ_TILBAKEKREVINGSGRUNNLAG',
};

export default venteArsakType;
