const venteArsakType = {
  AVV_DOK: 'AVV_DOK',
  AVV_FODSEL: 'AVV_FODSEL',
  UTV_FRIST: 'UTV_FRIST',
  VENT_GRADERING_UTEN_BEREGNINGSGRUNNLAG: 'VENT_GRADERING_UTEN_BEREGNINGSGRUNNLAG',
  VENT_PÅ_TILBAKEKREVINGSGRUNNLAG: 'VENT_PÅ_TILBAKEKREVINGSGRUNNLAG',
  AVV_RESPONS_REVURDERING: 'AVV_RESPONS_REVURDERING',
  FOR_TIDLIG_SOKNAD: 'FOR_TIDLIG_SOKNAD',
  VENT_PÅ_SISTE_AAP_ELLER_DP_MELDEKORT: 'VENT_PÅ_SISTE_AAP_MELDEKORT',
  ANKE_VENTER_PAA_MERKNADER_FRA_BRUKER: 'ANKE_VENTER_PAA_MERKNADER_FRA_BRUKER',
  ANKE_OVERSENDT_TIL_TRYGDERETTEN: 'ANKE_OVERSENDT_TIL_TRYGDERETTEN',
  VENT_OPDT_INNTEKTSMELDING: 'VENT_OPDT_INNTEKTSMELDING',
  VENT_OPPTJENING_OPPLYSNINGER: 'VENT_OPPTJENING_OPPLYSNINGER',
};

export default venteArsakType;
