const vilkarType = {
  FODSELSVILKARET_MOR: 'FP_VK_1',
  SVANGERSKAPVILKARET: 'SVP_VK_1',
  MEDLEMSKAPSVILKARET: 'FP_VK_2',
  MEDLEMSKAPSVILKÅRET_LØPENDE: 'FP_VK_2_L',
  SOKNADFRISTVILKARET: 'FP_VK_3',
  ADOPSJONSVILKARET: 'FP_VK_4',
  OMSORGSVILKARET: 'FP_VK_5',
  FORELDREANSVARSVILKARET_2_LEDD: 'FP_VK_8',
  FODSELSVILKARET_FAR: 'FP_VK_11',
  ADOPSJONSVILKARET_FORELDREPENGER: 'FP_VK_16',
  OPPTJENINGSPERIODE: 'FP_VK_21',
  OPPTJENINGSVILKARET: 'FP_VK_23',
  FORELDREANSVARSVILKARET_4_LEDD: 'FP_VK_33',
  SOKERSOPPLYSNINGSPLIKT: 'FP_VK_34',
  BEREGNINGSGRUNNLAGVILKARET: 'FP_VK_41',
};

export const fodselsvilkarene = [vilkarType.FODSELSVILKARET_MOR, vilkarType.FODSELSVILKARET_FAR];
export const adopsjonsvilkarene = [vilkarType.ADOPSJONSVILKARET, vilkarType.ADOPSJONSVILKARET_FORELDREPENGER];

export default vilkarType;
