const tilbakekrevingCodes = {
  FORSTÅTT: 'FORSTÅTT',
  FEILAKTIGEOPPLYSNINGER: 'FEILAKTIGEOPPLYSNINGER',
  MANGELFULLEOPPLYSNINGER: 'MANGELFULLEOPPLYSNINGER',
  GODTRO: 'GODTRO',
  FORSETT: 'FORSETT',
  GROVUAKTSOMHET: 'GROVUAKTSOMHET',
  SIMPELUAKTSOMHET: 'SIMPELUAKTSOMHET',
};

export default tilbakekrevingCodes;
