const sarligGrunn = {
  GRAD_AV_UAKTSOMHET: 'GRAD_AV_UAKTSOMHET',
  HELT_ELLER_DELVIS_NAVS_FEIL: 'HELT_ELLER_DELVIS_NAVS_FEIL',
  STOERRELSE_BELOEP: 'STOERRELSE_BELOEP',
  TID_FRA_UTBETALING: 'TID_FRA_UTBETALING',
  ANNET: 'ANNET',
};

export default sarligGrunn;
