const vilkarResultat = {
  FORSTO_BURDE_FORSTAATT: 'FORSTO_BURDE_FORSTAATT',
  FEIL_OPPLYSNINGER: 'FEIL_OPPLYSNINGER',
  MANGELFULL_OPPLYSNING: 'MANGELFULL_OPPLYSNING',
  GOD_TRO: 'GOD_TRO',
};

export default vilkarResultat;
