export const ISO_DATE_FORMAT = 'YYYY-MM-DD';
export const DDMMYYYY_DATE_FORMAT = 'DD.MM.YYYY';
export const HHMM_TIME_FORMAT = 'HH:mm';

export const ACCEPTED_DATE_INPUT_FORMATS = [DDMMYYYY_DATE_FORMAT, 'DDMMYYYY', 'DD-MM-YYYY', 'DD/MM/YYYY'];
