const dokumentMalType = {
  INNHENT_DOK: 'INNHEN',
  REVURDERING_DOK: 'REVURD',
  FORLENGET_DOK: 'FORLEN',
  FORLENGET_MEDL_DOK: 'FORLME',
  VEDTAK_MEDHOLD: 'VEDMED',
  KLAGE_AVVIST_DOK: 'KLAGAV',
  KLAGE_YTELSESVEDTAK_STADFESTET_DOK: 'KLAGVE',
  KLAGE_YTELSESVEDTAK_OPPHEVET_DOK: 'KLAGNY',
  KLAGE_OVERSENDT_KLAGEINSTANS_DOK: 'KLAGOV',
};

export default dokumentMalType;
