const klageVurdering = {
  STADFESTE_YTELSESVEDTAK: 'STADFESTE_YTELSESVEDTAK',
  MEDHOLD_I_KLAGE: 'MEDHOLD_I_KLAGE',
  OPPHEVE_YTELSESVEDTAK: 'OPPHEVE_YTELSESVEDTAK',
  AVVIS_KLAGE: 'AVVIS_KLAGE',
};

export default klageVurdering;
