const klageVurdering = {
  STADFESTE_YTELSESVEDTAK: 'STADFESTE_YTELSESVEDTAK',
  MEDHOLD_I_KLAGE: 'MEDHOLD_I_KLAGE',
  OPPHEVE_YTELSESVEDTAK: 'OPPHEVE_YTELSESVEDTAK',
  AVVIS_KLAGE: 'AVVIS_KLAGE',
  HJEMSENDE_UTEN_Å_OPPHEVE: 'HJEMSENDE_UTEN_Å_OPPHEVE',
};

export default klageVurdering;
