const oppholdArsakType = {
  INGEN: 'INGEN',
  UTTAK_MØDREKVOTE_ANNEN_FORELDER: 'UTTAK_MØDREKVOTE_ANNEN_FORELDER',
  UTTAK_FEDREKVOTE_ANNEN_FORELDER: 'UTTAK_FEDREKVOTE_ANNEN_FORELDER',
  UTTAK_FELLESP_ANNEN_FORELDER: 'UTTAK_FELLESP_ANNEN_FORELDER',
  UTTAK_FORELDREPENGER_ANNEN_FORELDER: 'UTTAK_FORELDREPENGER_ANNEN_FORELDER',
  UDEFINERT: '-',
};

export const oppholdArsakKontoNavn = {
  INGEN: 'Ingen årsak',
  UTTAK_MØDREKVOTE_ANNEN_FORELDER: 'Mødrekvote',
  UTTAK_FEDREKVOTE_ANNEN_FORELDER: 'Fedrekvote',
  UTTAK_FELLESP_ANNEN_FORELDER: 'Fellesperiode',
  UTTAK_FORELDREPENGER_ANNEN_FORELDER: 'Foreldrepenger',
  UDEFINERT: '-',
};

export const oppholdArsakMapper = {
  INGEN: 'UDEFINERT',
  UTTAK_MØDREKVOTE_ANNEN_FORELDER: 'MØDREKVOTE',
  UTTAK_FEDREKVOTE_ANNEN_FORELDER: 'FEDREKVOTE',
  UTTAK_FELLESP_ANNEN_FORELDER: 'FELLESPERIODE',
  UTTAK_FORELDREPENGER_ANNEN_FORELDER: 'FORELDREPENGER',
};

export default oppholdArsakType;
