const stonadskontoType = {
  FELLESPERIODE: 'FELLESPERIODE',
  MODREKVOTE: 'MØDREKVOTE',
  FEDREKVOTE: 'FEDREKVOTE',
  FORELDREPENGER: 'FORELDREPENGER',
  FLERBARNSDAGER: 'FLERBARNSDAGER',
  FORELDREPENGER_FOR_FODSEL: 'FORELDREPENGER_FØR_FØDSEL',
  UDEFINERT: '-',
};

export default stonadskontoType;
