const uttakArbeidType = {
  ORDINÆRT_ARBEID: 'ORDINÆRT_ARBEID',
  FRILANS: 'FRILANS',
  SELVSTENDIG_NÆRINGSDRIVENDE: 'SELVSTENDIG_NÆRINGSDRIVENDE',
  ANNET: 'ANNET',
};

export default uttakArbeidType;
