// Definerer alle behandlingspunktene. Desse verdien blir også vist i URL og brukt i historikk-elementene.
const behandlingspunktCodes = {
  ADOPSJON: 'adopsjon',
  AVREGNING: 'simulering',
  BEHANDLE_INNSYN: 'behandle_innsyn',
  BEREGNING: 'beregning',
  BEREGNINGSGRUNNLAG: 'beregningsgrunnlag',
  DEFAULT: 'default',
  FOEDSEL: 'foedsel',
  FORELDREANSVAR: 'foreldreansvar',
  KLAGE_NAV_FAMILIE_OG_PENSJON: 'klage_nav_familie_og_pensjon',
  KLAGE_NAV_KLAGEINSTANS: 'klage_nav_klageinstans',
  FORMKRAV_KLAGE_NAV_KLAGEINSTANS: 'formkrav_klage_nav_klageinstans',
  FORMKRAV_KLAGE_NAV_FAMILIE_OG_PENSJON: 'formkrav_klage_nav_familie_og_pensjon',
  MEDLEMSKAP: 'medlemskap',
  FORTSATTMEDLEMSKAP: 'fortsattmedlemskap',
  OMSORG: 'omsorg',
  OPPLYSNINGSPLIKT: 'opplysningsplikt',
  OPPTJENING: 'opptjening',
  SAKSOPPLYSNINGER: 'saksopplysninger',
  SOEKNADSFRIST: 'soeknadsfrist',
  TILBAKEKREVING: 'tilbakekreving',
  TILKJENT_YTELSE: 'tilkjent_ytelse',
  VARSEL: 'varsel',
  VEDTAK: 'vedtak',
  UTTAK: 'uttak',
  SIMULERING: 'simulering',
  KLAGE_RESULTAT: 'resultat',
};

export default behandlingspunktCodes;
