const ankeOmgjorArsak = {
  NYE_OPPLYSNINGER: 'NYE_OPPLYSNINGER',
  ULIK_REGELVERKSTOLKNING: 'ULIK_REGELVERKSTOLKNING',
  ULIK_VURDERING: 'ULIK_VURDERING',
  PROSESSUELL_FEIL: 'PROSESSUELL_FEIL',
};

export default ankeOmgjorArsak;
