const behandlingArsakType = {
  FEIL_I_LOVANDVENDELSE: 'RE-LOV',
  FEIL_REGELVERKSFORSTAELSE: 'RE-RGLF',
  FEIL_ELLER_ENDRET_FAKTA: 'RE-FEFAKTA',
  FEIL_PROSESSUELL: 'RE-PRSSL',
  ETTER_KLAGE: 'ETTER_KLAGE',
  ANNET: 'RE-ANNET',
  KLAGE_U_INNTK: 'RE-KLAG-U-INNTK',
  KLAGE_M_INNTK: 'RE-KLAG-M-INNTK',
  MEDLEMSKAP: 'RE-MDL',
  OPPTJENING: 'RE-OPTJ',
  FORDELING: 'RE-FRDLING',
  INNTEKT: 'RE-INNTK',
  DØD: 'RE-DØD',
  SØKERS_RELASJON: 'RE-SRTB',
  SØKNADSFRIST: 'RE-FRIST',
  BEREEGNINGSGRUNNLAG: 'RE-BER-GRUN',
  RE_TILSTØTENDE_YTELSE_INNVILGET: 'RE-TILST-YT-INNVIL',
  RE_ENDRING_BEREGNINGSGRUNNLAG: 'RE-ENDR-BER-GRUN',
  RE_TILSTØTENDE_YTELSE_OPPHØRT: 'RE-TILST-YT-OPPH',
  RE_ENDRING_FRA_BRUKER: 'RE-END-FRA-BRUKER',
};

export default behandlingArsakType;
