const inntektskategorier = {
  ARBEIDSTAKER: 'ARBEIDSTAKER',
  FRILANSER: 'FRILANSER',
  SELVSTENDIG_NÆRINGSDRIVENDE: 'SELVSTENDIG_NÆRINGSDRIVENDE',
  DAGPENGER: 'DAGPENGER',
  ARBEIDSAVKLARINGSPENGER: 'ARBEIDSAVKLARINGSPENGER',
  SJØMANN: 'SJØMANN',
  DAGMAMMA: 'DAGMAMMA',
  JORDBRUKER: 'JORDBRUKER',
  FISKER: 'FISKER',
  ARBEIDSTAKER_UTEN_FERIEPENGER: 'ARBEIDSTAKER_UTEN_FERIEPENGER',
  UDEFINERT: '-',
};

const SELVSTENDIG_NÆRINGSDRIVENDE_INNTEKTSKATEGORIER = [inntektskategorier.SELVSTENDIG_NÆRINGSDRIVENDE,
  inntektskategorier.JORDBRUKER, inntektskategorier.DAGMAMMA, inntektskategorier.FISKER];

export const isSelvstendigNæringsdrivende = inntektskategori => (SELVSTENDIG_NÆRINGSDRIVENDE_INNTEKTSKATEGORIER.includes(inntektskategori));

export default inntektskategorier;
