const kodeverkTyper = {
  ARBEID_TYPE: 'ArbeidType',
  AVSLAGSARSAK: 'Avslagsårsak',
  INNVILGET_AARSAK: 'InnvilgetÅrsak',
  VENTEARSAK: 'Venteårsak',
  BEHANDLING_ARSAK_TYPE: 'BehandlingÅrsakType',
  KLAGE_AVVIST_ARSAK: 'KlageAvvistÅrsak',
  KLAGE_MEDHOLD_ARSAK: 'KlageMedholdÅrsak',
  OMSORGSOVERTAKELSE_VILKAR_TYPE: 'OmsorgsovertakelseVilkårType',
  MEDLEMSKAP_MANUELL_VURDERING_TYPE: 'MedlemskapManuellVurderingType',
  VERGE_TYPE: 'VergeType',
  LANDKODER: 'Landkoder',
  MORS_AKTIVITET: 'MorsAktivitet',
  VIRKSOMHET_TYPE: 'VirksomhetType',
  OVERFOERING_AARSAK_TYPE: 'OverføringÅrsak',
  PERSONSTATUS_TYPE: 'PersonstatusType',
  FAGSAK_STATUS: 'FagsakStatus',
  RELATERT_YTELSE_TILSTAND: 'RelatertYtelseTilstand',
  RELATERT_YTELSE_TYPE: 'RelatertYtelseType',
  FAGSAK_YTELSE_TYPE: 'FagsakYtelseType',
  FORELDRE_TYPE: 'ForeldreType',
  FAMILIE_HENDELSE_TYPE: 'FamilieHendelseType',
  INNSYN_RESULTAT_TYPE: 'InnsynResultatType',
  BEHANDLING_TYPE: 'BehandlingType',
  OPPHOLD_ARSAK: 'OppholdÅrsak',
  UTSETTELSE_ARSAK: 'UtsettelseÅrsak',
  UTSETTELSE_GRADERING_KVOTE: 'UttakPeriodeType',
  OPPTJENING_AKTIVITET_TYPE: 'OpptjeningAktivitetType',
  UTTAK_PERIODE_TYPE: 'UttakPeriodeType',
  REVURDERING_VARSLING_ÅRSAK: 'RevurderingVarslingÅrsak',
  UTTAK_PERIODE_VURDERING_TYPE: 'UttakPeriodeVurderingType',
  UTTAK_AVSLAG_ARSAK: 'IkkeOppfyltÅrsak',
  INNTEKTSKATEGORI: 'Inntektskategori',
  BEREGNINGSGRUNNLAG_ANDELTYPER: 'BeregningsgrunnlagAndeltype',
  AKTIVITET_STATUS: 'AktivitetStatus',
  ARBEIDSKATEGORI: 'Arbeidskategori',
  FAGSYSTEM: 'Fagsystem',
  REGION: 'Region',
  SIVILSTAND_TYPE: 'SivilstandType',
  DOKUMENT_TYPE_ID: 'DokumentTypeId',
  FAKTA_OM_BEREGNING_TILFELLE: 'FaktaOmBeregningTilfelle',
  GRADERING_AVSLAG_AARSAK: 'GraderingAvslagÅrsak',
  SKJERMLENKE_TYPE: 'SkjermlenkeType',
};

export default kodeverkTyper;
